### ISSUE TITLE
Rename Netlify page to have a better url

### ISSUE THREAD

**Issue by aarongarciah** [jhardy/figma-styled-components#22]
The Netlify app can be renamed in the settings in order to have a better url like https://figma-styled-components.netlify.com which is free at the moment.

<img width="932" alt="Screenshot 2020-03-30 at 14 16 41" src="https://user-images.githubusercontent.com/7225802/77911671-7c552280-7291-11ea-8caf-884477472d3f.png">

**Comment by jhardy** [comment]
@aarongarciah Thanks for the heads tip! I've updated it.
